 language: node_js
 node_js:
         - "7"
 branches:
         only:
                 - master
 script:
         - npm i
         - node index.html
 cache:
         directories:
                 - node_modules
