language: node_js
node_js:
  - stable
branches:
  only:
    - deploy
deploy:
  local_dir: dist
  provides: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: deploy
